version: '3.8'

services:
  ai-api-gateway:
    image: ai-api-gateway
    container_name: ai-api-gateway
    build: .
    ports:
      - "13102:13102"
    volumes:
      - .:/app


# sudo docker compose build
